#!/bin/sh

DAEMON="apocrypha"
PIDFILE="/run/$DAEMON.pid"

start() {
    printf 'Starting %s: ' "$DAEMON"
    cd /mnt
    start-stop-daemon -m -S -q -p "$PIDFILE" -x "/usr/bin/$DAEMON"
    status=$?
    if [ "$status" -eq 0 ]; then
	echo "OK"
    else
	echo "FAIL"
    fi
    return "$status"
}

start
